### PR TITLE
Sketching out some ideas about preserving unknown vcard values

### PR DESCRIPTION
**Pull request by hendotcat**
Been messing around with @untitaker's idea about preserving unknown vcard data. That idea in PR #52 gave me the inspiration for getting started with this.

This PR currently doesn't work right. It's too good at preserving values, so much so that it's impossible to delete anything. The whole approach of my `merge()` function is fundamentally wrong.

My best idea so far to replace it with involves a list of regexes such as `^PHOTO`. Any line in the original vcard that matches one of the regexes gets copied into the modified vcard.

### CODE REVIEW

**Comment by untitaker** [comment]
I'm unsure how you'd do it in Ruby, but in Python I'd rather store all the data in the vcard object, and define [Python properties](http://www.programiz.com/python-programming/property) that reflect the state of each VCard property (instead of all the extract/merge biz)

**Comment by untitaker** [comment]
Any updates on this?

**Comment by hnrysmth** [comment]
I eventually gave up on it. Preserving unknown values is a bit of a nightmare once you start looking at the real-world data such as stuff exported from Apple's contacts app. Simple things like addresses aren't actually getting stored in a simple `ADR` field. Instead it's more like `item1.ADR`, `item2.ADR` and so on.

Once I started to think about the implications of preserving *that* data, making it readable & writable in ppl, all without breaking it for external apps, I began to realise what a tough little problem this is. It feels like it's probably a waaaay bigger job than it originally seemed. Sorry!

**Comment by untitaker** [comment]
Preserving fields is a different thing than actually supporting them. I guess you just don't want to open `ppl` up to that usecase at all, because eventually you'd be getting feature requests to support the weird constructs as well?

**Comment by hendotcat** [comment]
Closing this for now but I'm working on getting the project in general back on its feet a little so good news on balance I think!

**Pull request closed without merging**
